APPS-2546 switch to typography component
openlattice/child-care pull request #173
Opened 2020-12-02 22:41 UTC by bergieboy

2020-12-03 00:03 UTC, UnsungHero97 requested changes

2020-12-03 00:03 UTC, UnsungHero97 commented on src/components/layout/index.js
> +  font-size: 14px;
Please use rem units. `0.875rem` is 14px.

2020-12-03 18:38 UTC, UnsungHero97 approved these changes

2020-12-08 18:21 UTC, UnsungHero97 approved these changes

2020-12-08 18:25 UTC, giuliacampana approved these changes

2020-12-08 18:25 UTC, merged