California Branding & Navigation Redesign
openlattice/child-care pull request #197
Opened 2020-12-18 00:39 UTC by bergieboy

- APPS-2613 | Task 1: Add CA.gov and CDSS logos
- APPS-2614 | Task 2: Update mobile header
- APPS-2625 | Task 3 & 4: Update desktop version header

California has requested style changes to match their branding. This includes colors and logo. Updates to how navigation is rendered for desktop v mobile are also included in this PR. 

![Screen Shot 2020-12-17 at 4 35 50 PM](https://user-images.githubusercontent.com/19995069/102560029-19f1bb80-4086-11eb-96be-8651e846f7e4.png)
![localhost_9000_(iPhone X) (2)](https://user-images.githubusercontent.com/19995069/102560116-51606800-4086-11eb-8592-a1e0af12fc7d.png)
![localhost_9000_(iPhone X) (3)](https://user-images.githubusercontent.com/19995069/102560125-545b5880-4086-11eb-92ff-72b8b9de7eb0.png)

2020-12-18 17:11 UTC, anzioka commented on src/containers/app/AppHeaderContainer.js
> +        <AppHeaderNavagation />
Looks like a typo.

2020-12-18 17:20 UTC, bergieboy commented on src/containers/app/AppHeaderContainer.js
> +        <AppHeaderNavagation />
lol

2020-12-18 17:26 UTC, anzioka approved these changes

2020-12-31 17:29 UTC, UnsungHero97 requested changes

2020-12-31 17:29 UTC, UnsungHero97 commented on src/assets/svg/calIcon.svg
> +<image id="image0" width="192" height="192" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyZpVFh0WE1MOmNvbS5hZG9iZ
This should really just be a png file instead of an svg with an embedded image. Switching to png will also greatly reduce the file size.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/assets/svg/cdssLogo.svg
> +<image id="image0" width="600" height="150" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAACWCAYAAAACG/YxAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAP+lSURBV
Same comment about switching to png.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/assets/svg/chromeicon.svg
> +<image id="image0" width="400" height="300" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAAgAElEQVR4Ae2dB3xUVfbH2f82gmXtBaUFFbArIimUaekJPRBEEFFBwLprXV2XVddVE0BAQLr0D
Same comment about switching to png.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/assets/svg/edgeicon.svg
> +<image id="image0" width="1200" height="800" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABLAAAAMgCAYAAAAz4JsCAAAgAElEQVR4Aey9eYyl95WeJ40dJ45tOIDHjhE7EyMI7LHq3ltr7wubbFLLjJFMJh4kY8ewHf+R
Same comment about switching to png.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/assets/svg/firefoxicon.svg
> +<image id="image0" width="512" height="512" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAgAElEQVR4Aey9B5ScZ5Utqpm5w1ze3DXvrfcYSW3LysYBZ8VWB4VWsC2pgTsDzMAMDHMXLAaGO
Same comment about switching to png.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/assets/svg/safariicon.svg
> +<image id="image0" width="720" height="340" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAtAAAAFUCAYAAAANngvPAAAgAElEQVR4Aey9d5Tc5ZWnvzM7uzM7Z86Zf3b2zO7s8ez+dmb30JVaIhgw2B6DbWzAwGB7nMEeb
Same comment about switching to png.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/components/logos/CDSS.js
> +  width: 136px;
Setting thee height and width doesn't seem necessary as it's hardcoded in the svg. Also, if you switch to png, you'll get these exact dimensions.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/components/logos/CaGov.js
> +  width: 34px;
Same comment about height and width.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/components/logos/Chrome.js
> +  width: 40px;
Same comment about height and width.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/components/logos/Edge.js
> +  width: 40px;
Same comment about height and width.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/components/logos/Firefox.js
> +  width: 40px;
Same comment about height and width.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/components/logos/Safari.js
> +  width: 40px;
Same comment about height and width.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/core/style/Colors.js
> +  BLUE: '#046B99'
I see you're using LUK blue colors in other places, so what is this for? Perhaps rename to like `CA_BLUE`?

2020-12-31 17:29 UTC, UnsungHero97 commented on src/utils/constants/URLs.js
> +export const REGISTER_TO_VOTE_URL = 'https://registertovote.ca.gov/';
No change required, just a note on how I do this. I prefer to name this kind of file to `index.js`, and then I import like this:

```
import { FEEDBACK_EMAIL } from '../utils/constants';
```

Pro: less typing to import.

2020-12-31 17:29 UTC, UnsungHero97 commented on src/utils/constants/URLs.js
> +export const FEEDBACK_EMAIL = 'mychildcare@dss.ca.gov';
I think I saw this same constant in one of the other files.

2021-01-04 17:39 UTC, UnsungHero97 approved these changes

2021-01-04 19:37 UTC, anzioka approved these changes

2021-01-04 19:38 UTC, merged